# Generated by Django 2.0.2 on 2018-11-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0006_auto_20181105_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.CharField(max_length=50, verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='habilidad',
            fields=[
                ('idHabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('habilidad', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'habilidades',
            },
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=50, verbose_name='Pregunta')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('idRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('Respuesta', models.CharField(max_length=50, verbose_name='Habilidad')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name_plural': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='tipoActividad',
            fields=[
                ('idTipoAct', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Tipos Actividades',
            },
        ),
        migrations.CreateModel(
            name='tipoPregunta',
            fields=[
                ('idTipoPreg', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Preguntas',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipoPregunta', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='habilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.habilidad', verbose_name='Habilidad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='idLeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.leccion', verbose_name='Leccion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipoActividad', verbose_name='Tipo'),
        ),
    ]
