# Generated by Django 2.0.2 on 2018-11-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta',
            options={'verbose_name_plural': 'respuestas'},
        ),
    ]
