# Generated by Django 2.0.2 on 2018-11-08 21:35

import actividades.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20181106_2353'),
        ('actividades', '0003_diccionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='examen',
            fields=[
                ('idExamen', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(verbose_name='Calificacion')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('idUnidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name_plural': 'examenes',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('idMultimedia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('archivo', models.FileField(upload_to='files', verbose_name='Archivo')),
            ],
            options={
                'verbose_name_plural': 'Multimedias',
            },
        ),
        migrations.CreateModel(
            name='resultados',
            fields=[
                ('idResultado', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.FloatField(max_length=50, verbose_name='calificacion')),
                ('idExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.examen', verbose_name='examen')),
            ],
            options={
                'verbose_name_plural': 'resultados',
            },
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='idPregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=djongo.models.fields.EmbeddedModelField(model_container=actividades.models.respuesta, null=True),
        ),
        migrations.DeleteModel(
            name='respuesta',
        ),
    ]
