# Generated by Django 2.0.2 on 2018-11-08 22:48

import actividades.models
from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_auto_20181108_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='examen',
            name='preguntas',
            field=djongo.models.fields.ArrayModelField(default=django.utils.timezone.now, model_container=actividades.models.pregunta),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='pregunta',
        ),
    ]
