# Generated by Django 2.0.2 on 2018-11-08 23:00

import actividades.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20181108_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=50, verbose_name='Pregunta')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('respuesta', djongo.models.fields.EmbeddedModelField(model_container=actividades.models.respuesta, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipoPregunta', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'preguntas',
            },
        ),
        migrations.RemoveField(
            model_name='examen',
            name='preguntas',
        ),
    ]
