# Generated by Django 2.0.2 on 2018-11-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_auto_20181108_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='preguntas',
            field=models.ManyToManyField(to='actividades.pregunta'),
        ),
    ]
