# Generated by Django 2.0.2 on 2018-11-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_examen_preguntas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='nombre',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='examen',
            name='nombre',
            field=models.CharField(default='examen1', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
