# Generated by Django 2.0.2 on 2018-11-09 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_auto_20181108_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha dde examen'),
        ),
    ]
