# Generated by Django 2.0.2 on 2018-11-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_auto_20181108_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='preguntas',
        ),
    ]
