# Generated by Django 2.0.2 on 2018-11-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_remove_examen_preguntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='idUnidad',
        ),
        migrations.RemoveField(
            model_name='resultados',
            name='idExamen',
        ),
        migrations.DeleteModel(
            name='examen',
        ),
    ]
