# Generated by Django 2.0.2 on 2018-11-09 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20181106_2353'),
        ('actividades', '0011_auto_20181108_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='examen',
            fields=[
                ('idExamen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('calificacion', models.IntegerField(verbose_name='Calificacion')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha dde examen')),
                ('idUnidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name_plural': 'examenes',
            },
        ),
        migrations.AddField(
            model_name='resultados',
            name='idExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.examen', verbose_name='examen'),
            preserve_default=False,
        ),
    ]
