# Generated by Django 2.0.2 on 2018-11-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_auto_20181108_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='preguntas',
            field=models.ManyToManyField(to='actividades.pregunta'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Archivo'),
        ),
    ]
