# Generated by Django 2.0.2 on 2018-11-13 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_auto_20181109_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='instrucciones',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Instrucciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
