# Generated by Django 2.0.2 on 2018-10-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_auto_20181024_1518'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='idDocente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='docente.docente', verbose_name='Docente'),
            preserve_default=False,
        ),
    ]
