# Generated by Django 2.0.2 on 2018-10-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='curso',
            new_name='cursos',
        ),
    ]
