# Generated by Django 2.0.2 on 2018-10-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20181015_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cursos',
            new_name='curso',
        ),
    ]
