# Generated by Django 2.0.2 on 2018-10-16 08:17

import cursos.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20181015_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='Leccion',
            field=djongo.models.fields.EmbeddedModelField(model_container=cursos.models.leccion, null=True),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='tema',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='idCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
