# Generated by Django 2.0.2 on 2018-10-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20181016_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='Leccion',
        ),
    ]
