# Generated by Django 2.0.2 on 2018-11-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_unidad_leccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='diccionario',
            fields=[
                ('idDiccionario', models.AutoField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=50, verbose_name='Palabra')),
                ('significado', models.CharField(max_length=50, verbose_name='Significado')),
                ('imagen', models.ImageField(upload_to='projects', verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'diccionarios',
            },
        ),
        migrations.AlterField(
            model_name='leccion',
            name='idUnidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.unidad', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='diccionario',
            name='idLeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.leccion', verbose_name='Leccion'),
        ),
    ]
