# Generated by Django 2.0.2 on 2018-11-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_auto_20181106_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diccionario',
            name='idLeccion',
        ),
        migrations.DeleteModel(
            name='diccionario',
        ),
    ]
