# Generated by Django 2.0.2 on 2018-11-13 05:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20181106_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name=' Contenido '),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='tema',
            field=ckeditor.fields.RichTextField(verbose_name=' Contenido '),
        ),
    ]
