# Generated by Django 2.0.2 on 2018-11-15 06:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_auto_20181112_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name=' Nombre '),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='tema',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
