# Generated by Django 2.1.2 on 2018-10-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AulaVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=30)),
                ('miembros', models.ManyToManyField(through='docente.AulaVirtual', to='docente.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='aulavirtual',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.Grupo'),
        ),
    ]
