# Generated by Django 2.0.2 on 2018-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='docente',
            fields=[
                ('idDocente', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, verbose_name=' ')),
                ('apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido')),
                ('apellido_materno', models.CharField(max_length=30, verbose_name=' ')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
        ),
        migrations.RemoveField(
            model_name='aulavirtual',
            name='id_alumno',
        ),
        migrations.RemoveField(
            model_name='aulavirtual',
            name='id_grupo',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='miembros',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='AulaVirtual',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
