# Generated by Django 2.0.2 on 2018-10-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_iddocente'),
        ('docente', '0002_auto_20181024_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestroGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo', verbose_name='Grupo')),
            ],
        ),
    ]
