# Generated by Django 2.0.2 on 2018-11-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_maestrogrupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestrogrupo',
            name='idGrupo',
        ),
        migrations.DeleteModel(
            name='MaestroGrupo',
        ),
    ]
